dist: trusty
language: node_js
node_js:
  - "stable"
before_script:
  - npm install
script:
  - npm run build
env:
  global:
    - secure: "bhCRdGPLKm1RHjTJyxJ4RvKqGxmuiVGZIsYQFG5iZFJtrQW/N/A5Kt1sPxpQSbtJddR3MMIZH/4HJh8vNF2INCLY64Xs5j0MxxWclny7L9yGs7/NcDTMWlSJW/ClY2HcIXGrF
  fWgP/vcLKmKZo6x9sepAmagY9iwsNI4QetyIITdi4oEBLaEctjVTjC5du87IGK6yUIoQSjiCdPxDEGbHZkYEWn+5xbTXf/knZDIuGDxJMcavSRNRw+sBucgCsB1iFuecHPk56ERSIk53I69X
  plXUM8pc8k94eNduJoxVPviH4Cj0IvRbkMWGOt7fvasJRHeAGqpR2qL71LBtP0ADyqEc69+5dpdlNu9DkwsWN5TvcreIwvXFyqaK5yCfO0kYlRlyVGAcEsOYjAiy/+v7U5KkJ87qycvgtMQq
  516Zqz3MwqrtMraFZsADp5dfIcstV429oP909S4M0OgBHJU2MjSo7KNlr1o8Ak9BdEI1O4z5/kqQi0jvSAh0Jp2lkB/j24/JphdhO91EWjlGiJ+3JwASC53N6s92LMTkNwvgwW/7bP/7FMSX
  K0JZlDjllHS73373af2m/aqpt8jD2rxsue6K/k+PoUAizcAA+M2/nQdHO91cOXTTPjKpQfVbSAG4Pf7kmSEBsPXWPzEl21ptxvtbYCKxl8LuLXUlvSliqc="
    - VUE_APP_REDIRECT_URI="/implicit/callback"
    - VUE_APP_O4O_REDIRECT_URI="/o4o/callback"
    - VUE_APP_SCOPES="openid profile email"
    - VUE_APP_CLIENT_ID="0oaph3ep6uKllifkG0h7"
    - VUE_APP_ISSUER="https://byobrand.oktapreview.com/oauth2/default"
    - VUE_APP_API="https://oted1jcxcb.execute-api.us-east-2.amazonaws.com/stage/admin/api/v1"
    - VUE_APP_LOGO=https://upload.wikimedia.org/wikipedia/sco/2/21/Nvidia_logo.svg
    - VUE_APP_LOGO_INVERSE=https://s3.amazonaws.com/cms.ipressroom.com/219/files/20192/5c86452f2cfac2189166580b_NVIDIA-logo-BL/NVIDIA-logo-BL_eb2b6238-f291-47bd-9fce-dd4a4a75f07f-prv.jpg
    - VUE_APP_MAINCOLOR=#76b900
    - VUE_APP_COMPANY_NAME=NVIDIA

deploy:
  provider: s3
  access_key_id: "AKIAJCPFSIMCKHF7JP5A"
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "okta.idp.rocks"
  skip_cleanup: true
  local_dir: dist
